// AUTO-GENERATED by `npm run art:scan` (scripts/collectionArt/scanArt.ts). DO NOT EDIT BY HAND.
// 規格を満たすことを確認できた画像だけがここに載る。IDに対応するエントリが無い場合、
// src/ui/collectionArt.ts はnullを返しUI側は既存のアイコン絵文字表示へフォールバックする。

export interface CollectionArtEntry {
  id: string;
  domain: 'part' | 'enemy';
  file: string;
  width: number;
  height: number;
  hash: string;
}

export const COLLECTION_ART_ENTRIES: CollectionArtEntry[] = [
  { id: "final_chimera", domain: "enemy", file: "enemies/final_chimera.png", width: 256, height: 256, hash: "2e8e9d66f179d7397acba403e52c9414ff385c71cce95abbbb3990db2ac303fb" },
  { id: "insect_queen", domain: "enemy", file: "enemies/insect_queen.png", width: 256, height: 256, hash: "b844dd18976caeb763584ccd34988d9b450c4557a7498003426592a924108e9c" },
  { id: "poison_spider", domain: "enemy", file: "enemies/poison_spider.png", width: 256, height: 256, hash: "3a009ba6ea881612fa3a25d7921385e30639d605cdd0b5f0d88b53dd28ce6658" },
  { id: "dragon_claw", domain: "part", file: "parts/dragon_claw.png", width: 256, height: 256, hash: "e64a40436db8d3fd7f6af401acde1a81e6380e48d58bce0a248e3dac95736df6" },
  { id: "dragon_twin_heads", domain: "part", file: "parts/dragon_twin_heads.png", width: 256, height: 256, hash: "c5c764603d328b465cf4ac7febdb51b33d5c65b8349bda4cf0001b123a3fba29" },
  { id: "golem_ancient_core", domain: "part", file: "parts/golem_ancient_core.png", width: 256, height: 256, hash: "9e7b1658a595732819d83f005314f04c7b368e70abb67482a2d416a34ada83ca" },
  { id: "golem_giant_fist", domain: "part", file: "parts/golem_giant_fist.png", width: 256, height: 256, hash: "97f76dc8701384d6a801a6f9391322ea77eb3b7b81d3387f1096dda9c1280bbd" },
  { id: "insect_carapace", domain: "part", file: "parts/insect_carapace.png", width: 256, height: 256, hash: "f26254e165935cfc8f3edd89c89bf28ebca495f8b01ac71a892aa88866bc9969" },
  { id: "insect_sickle_arm", domain: "part", file: "parts/insect_sickle_arm.png", width: 256, height: 256, hash: "f39e680780f1dc5b94b15c87d6de613ab43477435d8744f7d9a3ed4f50746bdd" },
  { id: "special_colossal_heart", domain: "part", file: "parts/special_colossal_heart.png", width: 256, height: 256, hash: "424b467cf422d57a16674d5b5ee0d5ff94bbf6b77b7daed07a0f1a301b7c493e" },
  { id: "weak_arm", domain: "part", file: "parts/weak_arm.png", width: 256, height: 256, hash: "cd8fbbfbcf3e2cbb7aee2401071529ca112618292685e9ef4bdc4f6a6818e6c2" },
];
